<template>
  <v-dialog v-model="open" max-width="720" persistent>
    <v-card :title="`${title}を編集`"><v-card-text>
      <v-alert v-if="message" type="error" class="mb-4">{{ message }}</v-alert>
      <v-text-field v-model="form.name" label="名称" required />
      <v-text-field v-if="masterType === 'warrantyService'" v-model.number="form.defaultPeriodYears" label="標準保証期間（年）" type="number" min="1" required />
      <template v-if="masterType === 'property'"><v-select v-model="form.homeownerId" :items="references.homeowners" item-title="name" item-value="id" label="施主" required /><v-select v-model="form.constructionCompanyId" :items="references.companies" item-title="name" item-value="id" label="工務店" required /></template>
      <template v-if="masterType === 'property' || masterType === 'constructionCompany'"><v-text-field v-model="form.postalCode" label="郵便番号（7桁）" required /><v-text-field v-model="form.prefecture" label="都道府県" required /><v-text-field v-model="form.municipality" label="市区町村" required /><v-text-field v-model="form.streetTownAndNumber" label="町域・番地" required /><v-text-field v-model="form.buildingName" label="建物名（任意）" /></template>
      <template v-if="masterType === 'constructionCompany'"><v-text-field v-model="form.telephone" label="TEL（任意）" /><v-text-field v-model="form.fax" label="FAX（任意）" /><v-text-field v-model="form.contactPerson" label="担当者（任意）" /><v-textarea v-model="form.contactDetails" label="連絡先（任意）" /><v-text-field v-model="form.email" label="メールアドレス（任意）" /><v-textarea v-model="form.notes" label="備考（任意）" /></template>
      <template v-if="masterType === 'homeowner'"><v-alert type="info" variant="tonal" class="mb-3">住所の自動入力は未接続です。郵便番号を含め手入力してください。</v-alert><v-text-field v-model="form.postalCode" label="郵便番号（7桁）" required /><v-text-field v-model="form.prefecture" label="都道府県" required /><v-text-field v-model="form.municipality" label="市区町村" required /><v-text-field v-model="form.streetTownAndNumber" label="町域・番地" required /><v-text-field v-model="form.buildingName" label="建物名（任意）" /><v-text-field v-model="form.telephone" label="TEL（任意）" /><v-text-field v-model="form.fax" label="FAX（任意）" /><v-textarea v-model="form.notes" label="備考（任意）" /></template>
    </v-card-text><v-card-actions><v-spacer /><v-btn :disabled="saving" @click="open = false">キャンセル</v-btn><v-btn color="primary" :loading="saving" @click="save">更新</v-btn></v-card-actions></v-card>
  </v-dialog>
</template>
<script setup lang="ts">
import type { ManagedMaster, MasterType } from '../composables/useMasterManagement'
const props = defineProps<{ masterType: MasterType; title: string; row: ManagedMaster | null }>()
const emit = defineEmits<{ saved: [] }>()
const open = defineModel<boolean>({ required: true })
const { updateMaster, loadPropertyReferences } = useMasterManagement(props.masterType)
const saving = ref(false); const message = ref('')
const references = reactive({ homeowners: [] as ManagedMaster[], companies: [] as ManagedMaster[] })
const form = reactive<Record<string, any>>({})
const initialize = async () => { const row = props.row; if (!row) return; Object.assign(form, { name: row.name, defaultPeriodYears: row.defaultPeriodYears ?? 1, homeownerId: row.homeownerId ?? '', constructionCompanyId: row.constructionCompanyId ?? '', postalCode: row.address?.postalCode ?? '', prefecture: row.address?.prefecture ?? '', municipality: row.address?.municipality ?? '', streetTownAndNumber: row.address?.streetTownAndNumber ?? '', buildingName: row.address?.buildingName ?? '', telephone: row.telephone ?? '', fax: row.fax ?? '', contactPerson: row.contactPerson ?? '', contactDetails: row.contactDetails ?? '', email: row.email ?? '', notes: row.notes ?? '' }); if (props.masterType === 'property') Object.assign(references, await loadPropertyReferences(row)); message.value = '' }
watch(open, value => { if (value) void initialize() })
const fields = () => { if (props.masterType === 'warrantyService') return { name: form.name, defaultPeriodYears: form.defaultPeriodYears }; if (props.masterType === 'property') return { name: form.name, homeownerId: form.homeownerId, constructionCompanyId: form.constructionCompanyId, address: { postalCode: form.postalCode, prefecture: form.prefecture, municipality: form.municipality, streetTownAndNumber: form.streetTownAndNumber, buildingName: form.buildingName || null } }; if (props.masterType === 'constructionCompany') return { name: form.name, address: { postalCode: form.postalCode, prefecture: form.prefecture, municipality: form.municipality, streetTownAndNumber: form.streetTownAndNumber, buildingName: form.buildingName || null }, telephone: form.telephone || null, fax: form.fax || null, contactPerson: form.contactPerson || null, contactDetails: form.contactDetails || null, email: form.email || null, notes: form.notes || null }; if (props.masterType === 'homeowner') return { name: form.name, address: { postalCode: form.postalCode, prefecture: form.prefecture, municipality: form.municipality, streetTownAndNumber: form.streetTownAndNumber, buildingName: form.buildingName || null }, telephone: form.telephone || null, fax: form.fax || null, notes: form.notes || null }; return { name: form.name } }
const save = async () => { if (!props.row) return; saving.value = true; try { await updateMaster(props.row.id, fields()); open.value = false; emit('saved') } catch (error) { message.value = error instanceof Error ? error.message : '保存できませんでした。' } finally { saving.value = false } }
</script>
